// lib/data/supabase/models/site_profile.dart
// Data model that mirrors the columns in public.site_profile.
// Lets us convert between Supabase rows (Map) and a typed Dart object.

class SiteProfile {
  // Required fields (NOT NULL in DB)
  final String id; // generated by DB; we won’t set it on insert
  final String fullName; // maps to column: full_name
  final String title; // maps to column: title
  final String email; // maps to column: email

  // Optional fields (nullable in DB)
  final String? tagline; // tagline
  final String? aboutMd; // about_md (Markdown)
  final String? phone; // phone
  final String? linkedin; // linkedin
  final String? cvUrl; // cv_url
  final String? github; // github
  final String? twitter; // twitter
  final String? website; // website
  final String? location; // location
  final String? avatarUrl; // avatar_url

  SiteProfile({
    required this.id,
    required this.fullName,
    required this.title,
    required this.email,
    this.tagline,
    this.aboutMd,
    this.phone,
    this.linkedin,
    this.cvUrl,
    this.github,
    this.twitter,
    this.website,
    this.location,
    this.avatarUrl,
  });

  // Build a SiteProfile from a Supabase row (Map<String, dynamic>)
  factory SiteProfile.fromMap(Map<String, dynamic> m) => SiteProfile(
    id: m['id'] as String,
    fullName: m['full_name'] as String,
    title: m['title'] as String,
    email: m['email'] as String,
    tagline: m['tagline'] as String?,
    aboutMd: m['about_md'] as String?,
    phone: m['phone'] as String?,
    linkedin: m['linkedin'] as String?,
    cvUrl: m['cv_url'] as String?,
    github: m['github'] as String?,
    twitter: m['twitter'] as String?,
    website: m['website'] as String?,
    location: m['location'] as String?,
    avatarUrl: m['avatar_url'] as String?,
  );

  // Convert this object into a Map for insert/upsert/update in Supabase
  Map<String, dynamic> toMap() => {
    'full_name': fullName,
    'title': title,
    'email': email,
    'tagline': tagline,
    'about_md': aboutMd,
    'phone': phone,
    'linkedin': linkedin,
    'cv_url': cvUrl,
    'github': github,
    'twitter': twitter,
    'website': website,
    'location': location,
    'avatar_url': avatarUrl,
  };
}
